### ISSUE TITLE
How to update list rendering?

### ISSUE THREAD

**Issue by cipriano200** [realmorg/realm#54]
Realm is a nice concept, thank you.
Would like to know how to update a list of array from your example: https://realm.codes/examples/basics/list-rendering

**Comment by oknoorap** [comment]
Hey @cipriano200 🙇🏼 , thanks for giving Realm a try! While Realm is still in the works, we appreciate your support. To update the array state, you can leverage the power of `set-state`.

https://realm.codes/references/actions/set-state

For example you could use update / push the array with mutate `push` or `assign`,
https://codesandbox.io/s/example-list-rendering-forked-4w6xd7

**Comment by cipriano200** [comment]
That works.
Thanks for creating realm
